/**
 * Created by Douglas on 6/22/2017.
 */
export default [
    {
        name: `Emmet`,
        description: `Every day, Emmet goes to work exactly by the steps in the instructions booklet that he always keeps in his hand. As part of Bricksburg’s busy construction crew, he helps to rebuild the city as briefed by President Business.`,
        price: 9.99,
        imageUrl: `https://lc-www-live-s.legocdn.com/r/www/r/catalogs/-/media/catalogs/characters/minifigures/the%20lego%20movie/71004_detail_constructionemmet.jpg?l.r2=-185741075`,
        isActive: true,
    },
    {
        name: `Battle Dwarf`,
        description: `<p>“Five angry trolls and a rock giant? Hah, what else d’ya got?”</p><p>The Battle Dwarf is a fierce warrior of the Boar Clan, a brave and proud family renowned throughout the land for their expert iron-forging. He carries the axe Gougetusk, crafted by his own hand, and the legendary war hammer Snoutsmasher, famed for its ability to flatten enemies with the force of a charging razorback.</p><p>The Battle Dwarf is as loyal a friend as he is ferocious an opponent, though his hearty back-slaps of comradery are almost as likely to knock you over as a blow from his hammer. The tattoo on his shoulder recounts the tale of how he once faced a fire-breathing sea dragon. He didn’t manage to slay it or anything, but just getting away in one piece was considered a great heroic achievement – and the encounter left him with his magnificent new hairstyle, too!</p>`,
        price: 4.99,
        imageUrl: `https://lc-www-live-s.legocdn.com/r/www/r/catalogs/-/media/catalogs/characters/minifigures/series%2017/1488x837/1488x837-battledwarf.png?l.r2=-473110572`,
        isActive: true,
    },
    {
        name: `Yeti`,
        description: `<p>"Yoo-hoo! Here I am!”</p><p>Once upon a time, the Yeti was barely more than a legend. Dwelling all alone up on his snowy mountaintop, he was rarely glimpsed by travelers, and those who did spot him were even less often believed. The Yeti himself was starting to think that he might just be a myth.</p><p>But that changed the day he looked himself up on the internet. Everyone seemed to be talking about him there, and they knew all about him – from his favorite foods to his foot size. He was famous! Now that he knows he’s a celebrity, the no-longer-shy Yeti is just waiting for crowds of new friends to arrive. He can’t wait to meet them!</p>`,
        price: 8.99,
        imageUrl: `https://lc-www-live-s.legocdn.com/r/www/r/catalogs/-/media/catalogs/characters/minifigures/series%2011/71002_detail_snowman.jpg?l.r2=569864346`,
        isActive: true,
    },
    {
        name: `Sad Clown`,
        description: `To the Sad Clown, everything in life is a tragedy. Things that other Minifigures find joyful and jolly only fill him with sadness and woe. Not even puppies, kittens and birthday parties can turn his melancholy frown upside-down.`,
        price: 2.99,
        imageUrl: `https://lc-www-live-s.legocdn.com/r/www/r/catalogs/-/media/catalogs/characters/minifigures/series%2010/71001_detail_clown.jpg?l.r2=-488711161`,
        isActive: true,
    },
    {
        name: `Piggy Guy`,
        description: `The Piggy Guy used to be a regular farmer. Then one day he noticed how much fun his hogs were having, and he decided to try it out for himself! Donning a pink pig costume, he started to spend all of his time oinking, eating apples, and wallowing in the mud – and he found out that he really liked it.`,
        price: 0.99,
        imageUrl: `https://lc-www-live-s.legocdn.com/r/www/r/catalogs/-/media/catalogs/characters/minifigures/series%2012/71007_detail_pigsuitguy.jpg?l.r2=-278822024`,
        isActive: true,
    },
    {
        name: `Wiley Fusebot`,
        description: `Not every robot can represent the height of modern technology. Stationed in the Wild West in the guise of a scruffy gold prospector, Wiley Fusebot is rusty, broken-down, and almost totally unhinged.`,
        price: 1.99,
        imageUrl: `https://lc-www-live-s.legocdn.com/r/www/r/catalogs/-/media/catalogs/characters/minifigures/the%20lego%20movie/71004_detail_robocrocket.jpg?l.r2=-722453573`,
        isActive: true,
    },
    {
        name: `Where Are My Pants? Guy`,
        description: `The “Where Are My Pants?” Guy is the star of the #1 hit television show “Where Are My Pants?”, written, filmed, and broadcast by the Octan Studios subsidiary of President Business’s personal mega-corporation.`,
        price: 4.99,
        imageUrl: `https://lc-www-live-s.legocdn.com/r/www/r/catalogs/-/media/catalogs/characters/minifigures/the%20lego%20movie/71004_detail_pantsguy.jpg?l.r2=-1410203322`,
        isActive: true,
    },
    {
        name: `Hippie`,
        description: `“Make LEGO® models, not war!”  The friendly, good-natured Hippie loves everything in the entire world. Rain and shine, day and night, puppies and kittens – they all bring a happy smile to his face. With a fashion sense that hasn’t changed since the Sixties, he never stays in the same place for long, preferring to roam across city and countryside alike, stopping only to smell the flowers and spread his simple message of peace, love and LEGO bricks.`,
        price: 6.99,
        imageUrl: `https://lc-www-live-s.legocdn.com/r/www/r/catalogs/-/media/catalogs/characters/minifigures/series%207/8831_detail_hippie.jpg?l.r2=-856774881`,
        isActive: true,
    },
    {
        name: `Sailor`,
        description: `The brave and trusty Sailor can always be counted on in a nautical emergency. He can tie knots like nobody’s business, spot a lighthouse through his spyglass from a hundred leagues’ distance in the middle of a storm, and hoist a mainsail or batten down the hatches in no time flat.`,
        price: 2.99,
        imageUrl: `https://lc-www-live-s.legocdn.com/r/www/r/catalogs/-/media/catalogs/characters/minifigures/series%204/8804_detail_sailor.jpg?l.r2=-697107358`,
        isActive: true,
    },
    {
        name: `Sumo Wrestler`,
        description: `The Sumo Wrestler has dedicated his life to the ancient art of sumo. He has earned the nickname “The Immovable Object” for his ability to stand perfectly still while his opponent tries to push him over or out of the sumo ring. He’s recognized wherever he goes, and is always happy to stop and sign autographs for his many fans.`,
        price: 9.99,
        imageUrl: `https://lc-www-live-s.legocdn.com/r/www/r/catalogs/-/media/catalogs/characters/minifigures/series%203/8803_detail_sumo.jpg?l.r2=462651192`,
        isActive: true,
    },
    {
        name: `Gorilla Suit Guy`,
        description: `The Gorilla Suit Guy is a mystery. Who is he? Why is he wearing that suit? Does he think he’s an actual gorilla, or did he get lost on his way to a costume party? He certainly acts like the real thing, or at least like someone who’s watched a lot of old movies and TV shows and thinks that’s how a gorilla should act. And he sure is wild about bananas.`,
        price: 1.99,
        imageUrl: `https://lc-www-live-s.legocdn.com/r/www/r/catalogs/-/media/catalogs/characters/minifigures/series%203/8803_detail_gorilla.jpg?l.r2=768496794`,
        isActive: true,
    },
    {
        name: `Disco Dude`,
        description: `The Disco Dude has traveled back in time to relive the days of disco dancing, bell-bottom pants and the very first LEGO Space sets. He can’t help but love it! Whenever he hears a disco beat and sees the big disco ball lights start flashing, he gets caught up in the music and just can’t stop dancing.`,
        price: 4.99,
        imageUrl: `https://lc-www-live-s.legocdn.com/r/www/r/catalogs/-/media/catalogs/characters/minifigures/series%202/8684_detail_disco-dude.jpg?l.r2=-947480350`,
        isActive: true,
    },
    {
        name: `Wrestler`,
        description: `Only three things matter to the Super Wrestler: his mask, his honor, and the time-honored art of wrestling. He throws himself at every challenge that comes his way with gusto, counting on the strength of justice and his muscular arms to save the day, no matter the odds or danger. When victory is his, he throws out his arms to the sound of roaring cheers and wild applause…which is a little odd when there doesn’t seem to be anyone else around.`,
        price: 10.99,
        imageUrl: `https://lc-www-live-s.legocdn.com/r/www/r/catalogs/-/media/catalogs/characters/minifigures/series%201/8683_detail_wrestler.jpg?l.r2=-403279245`,
        isActive: true,
    },
    {
        name: `Demolition Dummy`,
        description: `The Demolition Dummy exists to take things apart. He is compelled to disassemble everything that he comes across into its component parts, leaving piles of pieces behind wherever he goes. Although he doesn’t seem to be very bright or creative, he is extremely persistent, and it’s difficult to stop him once he starts trying to deconstruct something. No matter what anyone else does, he always seems to find a way to accomplish his task.`,
        price: 9.99,
        imageUrl: `https://lc-www-live-s.legocdn.com/r/www/r/catalogs/-/media/catalogs/characters/minifigures/series%201/8683_detail_dummy.jpg?l.r2=-675281536`,
        isActive: true,
    },
    {
        name: `Caveman`,
        description: `This would-be inventor from the prehistoric past is always tinkering with sticks, rocks and the occasional bricks he finds lying around, trying to invent something new. Of course, everything he comes up with has already been invented – he’s a Caveman with a tiny little brain, after all – but that doesn’t stop him from trying. He never gets jokes and usually needs things explained to him with gestures and pictures…and even then, he gets it wrong most of the time.`,
        price: 1.99,
        imageUrl: `https://lc-www-live-s.legocdn.com/r/www/r/catalogs/-/media/catalogs/characters/minifigures/series%201/8683_detail_caveman.jpg?l.r2=501097693`,
        isActive: false,
    },
];